### PR TITLE
Install a DNS Resolver and Consul Template

### PR DESCRIPTION
**Pull request by nhuray**
Hi guys,

This pull request is very important for what we are building. 

Basically in this PR, I installed go-dnsmasq and Consul template supervised by S6, in order to be able to resolve DNS names through Consul on our ECS infrastructure.

Please take time to check the [README.md](https://github.com/nhuray/docker-alpine/blob/85b2339f7bf8e43ba38890294b86befa927336b5/README.md) to understand the motivation for this change.

Nik

### CODE REVIEW

**Review by csmchoi — APPROVED** [review]
It looks good to me.

**Comment by bratislavml** [comment]
👍

**Comment by nhuray** [comment]
Do you need more explanations ?

**Comment by bratislavml** [comment]
NO, everything is documented in comments

**Pull request merged**
